function n_in = number_threshold_v2(loop_size,n_bp,...
    MFE,fraction_in_stem,n_hairpin,cut,dist_stem_U,U_rich_bool,MFE_threshold)

n_in = [];
for i = 1:length(cut.bp_high)
    if U_rich_bool
        bool = (n_bp>=cut.bp_low(i)) & (n_bp<=cut.bp_high(i)) &...
            (loop_size>=cut.loop_low(i)) & (loop_size<=cut.loop_high(i)) &...
            dist_stem_U<=cut.distance_stem_end_thresh(i) & ...
            (fraction_in_stem>=cut.frac_low(i)) & ...
            (MFE<=-MFE_threshold) & ...
            (n_hairpin==1);
    else
        bool = (n_bp>=cut.bp_low(i)) & (n_bp<=cut.bp_high(i)) &...
            (loop_size>=cut.loop_low(i)) & (loop_size<=cut.loop_high(i)) &...
            (fraction_in_stem>=cut.frac_low(i)) & ...
            (MFE<=-MFE_threshold) & ...
            (n_hairpin==1);
    end
    n_in(i) = sum(bool);
end

